spring:
  application:
    name: RankCat
  task:
    scheduling:
      pool:
        size: 1
      thread-name-prefix: rankcat-scheduler-
  data:
    mongodb:
      uri: TEST
  #    #redis
  #    redis:
  #      host: localhost
  #      port: 6379
  datasource:
    url: TEST
    username: TEST
    password: TEST
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1058802701975-u0d4hrvhgc9lfqa7bs555n02pcqr0g8q.apps.googleusercontent.com
            client-secret: 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
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            client-id: 3AIdpZzADRyEQT9Rdxrb
            client-secret: fmRpK5rnLo
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - email
              - nickname
          kakao:
            client-id: 76cbc01f33b78a19c3f864bceca8c380
            # client-secret: [카카오 시크릿 키]   # 필요시 추가
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.naver.com
    port: 465
    username: TEST
    password: TEST
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true  # 반드시 추가!
      mail.smtp.ssl.trust: smtp.naver.com
    default-encoding: UTF-8

# naver search ad key
naver:
  search:
    ad:
      access-license: TEST
      secret-key:     TEST
      customer-id:    TEST

  shoppinginsight:
    client:
      id: hsrlivRHUW8r4n_eB7xw
      secret: lc0M_cVOmM

jwt:
  issuer: iwill324@pusan.ac.kr
  secret-key: TEST