spring:
  datasource:
    # MySQL 접속 정보
    url: jdbc:mysql://localhost:3306/rankcat?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL} # Docker 실행 시 설정한 MYSQL_ROOT_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update # 엔티티 구조를 DB 테이블에 자동으로 반영
    show-sql: true # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 정렬
        highlight_sql: true # SQL 문구에 색상 적용
    # MySQL 전용 문법(Dialect) 사용 설정
    database-platform: org.hibernate.dialect.MySQLDialect

cookie:
  same-site: Lax
  secure: false

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:5173