spring:
  application:
    name: RankCat
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DBNAME}?retryWrites=true&w=majority
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# naver search ad key
naver:
  search:
    ad:
      access-license: ${ACCESS_LICENSE}   # ACCESS_LICENSE ????
      secret-key:     ${SECRET_KEY}       # SECRET_KEY ????
      customer-id:    ${CUSTOMER_ID}      # CUSTOMER_ID ????
  shoppinginsight:
    client:
      id: ${CLIENT_ID}
      secret: ${CLIENT_SECRET}